defaults:
  - scope:
      path: "Images"
    values:
      headers:
        Cache-Control: "public, max-age=31536000"  # 1 an de cache pour les images
  - scope:
      path: "monrepository/style.css"
    values:
      headers:
        Cache-Control: "public, max-age=604800"  # 7 jours de cache pour le CSS
  - scope:
      path: "monrepository/java.js"
    values:
      headers:
        Cache-Control: "public, max-age=604800"  # 7 jours de cache pour le JavaScript
